name: cardiovascular-risk-prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - sqlalchemy
  - scipy
  - statsmodels
  - scikit-learn
  - imbalanced-learn
  - xgboost
  - graphviz
  - jupyter
